export const problems = {
    "Two Sum": 1,
    "Longest Substring Without Repeating Characters": 2,
    "Best Time to Buy and Sell Stock I": 3,
    "Best Time to Buy and Sell Stock II": 4,
    "Best Time to Buy and Sell Stock III": 5,
    "Best Time to Buy and Sell Stock IV": 6,
    "Sudoku Solver": 7,
    "Minimum Path Sum": 8,
    "Dungeon Game": 9,
    "Longest Increasing Path in a Matrix": 10,
    "Valid Parentheses": 11,
    "Generate Parentheses": 12,
    "Median of Two Sorted Arrays": 13,
    "Minimum Window Substring": 14,
    "Sliding Window Maximum": 15,
    "Last Stone Weight": 16,
    "Reverse Linked List": 17,
    "Merge Two Sorted Lists": 18,
    "Reverse Nodes in k-Group": 19,
    "Linked List Cycle": 20,
    "Reorder List": 21,
    "Remove Nth Node From End of List": 22,
    "Add Two Numbers": 23,
    "Find the Duplicate Number": 24,
    "Kth Largest Element in an Array": 25,
    "Word Search": 26,
    "Word Search II": 27,
    "Climbing Stairs": 28,
    "House Robber": 29,
    "House Robber II": 30,
    "Longest Palindromic Substring": 31,
    "Palindromic Substrings": 32,
    "Coin Change": 33,
    "Maximum Product Subarray": 34,
    "Longest Increasing Subsequence": 35,
    "Partition Equal Subset Sum": 36,
    "Longest Common Subsequence": 37,
    "Coin Change II": 38,
    "Maximum Subarray": 39,
    "Jump Game": 40,
    "Jump Game II": 41,
    "Number of 1 Bits": 42,
    "Counting Bits": 43,
    "Reverse Bits": 44,
    "Missing Number": 45,
    "Network Delay Time": 46,
    "Course Schedule": 47,
    "Cheapest Flights Within K Stops": 48,
    "Number of Islands": 49,
    "Rotting Oranges": 50,
    "Max Area of Island": 51
};
